package christmas.util.constant

enum class Values(val value: Int) {
    // DATE
    DATE_START(1),
    DATE_END(31),
    DATE_CHRISTMAS(25),

    // COUNT
    COUNT_MIN_MENU(1),
    COUNT_MAX_MENU(20),
    COUNT_WEEK(7),

    // PRICE
    PRICE_EVENT_THRESHOLD(10_000),
    PRICE_GIFT_THRESHOLD(120_000),
    PRICE_GIFT_EVENT(25_000),

    // DISCOUNT
    DISCOUNT_CHRISTMAS_START(1_000),
    DISCOUNT_CHRISTMAS_EACH_DAY(100),
    DISCOUNT_WEEKEND_OR_WEEKDAY(2_023),
    DISCOUNT_SPECIAL(1_000),
}